FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy app
COPY . .

# Run app
CMD gunicorn app:app --host 0.0.0.0 --port ${PORT:-8000}